# Dilack on severe synthetic motion deblurring (ImageNet).
conditioning:
  method: ps_dilack
  params:
    scale: 1.0
    deconv_scale: 1.0
    kernel_size: 256
    exp_task: motion_deblur_imagenet_dilack
    threshold_init: 0.2
    patch_size: 32
    skip_point: 500
    YS: 0

data:
  name: imagenet
  root: ./samples/dps_val/imagenet

measurement:
  operator:
    name: motion_blur
    kernel_size: 256
    intensity: 1.0
  noise:
    name: gaussian
    sigma: 0.0005
