# DPS (vanilla posterior sampling) baseline on the real Waller DiffuserCam data.
conditioning:
  method: ps_conv
  params:
    scale: 1.0
    diff_scale: 1.0
    deconv_scale: 1.0
    kernel_size: 256
    exp_task: lensless_real_waller_dps
    YS: 0

data:
  name: lensless_real_waller
  root: ./samples/dps_val/diffusercam_100

measurement:
  operator:
    name: lensless_real_waller
    kernel_size: 256
    intensity: 0.5
  noise:
    name: gaussian
    sigma: 0.002
