conditioning:
  method:  ps_conv
  params:
    scale: 1
    diff_scale: 1.0
    deconv_scale: 1.0
    kernel_size: 256
    exp_task: lensless_turing_syn_ffhq_dps

    YS : 0
    

data:
  name: ffhq #lensless_ys_admm
  root: ./samples/dps_val/ffhq #/data3/lensless_data/ys_v3_dj_sample_0/

measurement:
  operator:
    name: lensless_turing
    kernel_size: 256
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.002
