conditioning:
  method:  ps_roi_deconv_patch_kl_stochastic #ps_roi_deconv_patch_various_mask # ps_conv
  params:
    scale: 1.0
    deconv_scale: 1.0
    kernel_size: 256
    exp_task: lensless_turing_syn_imagenet_dilack

    threshold_init: 0.2 #0.75
    patch_size: 32
    skip_point : 500

    YS : 0

data:
  name: imagenet 
  root: ./samples/dps_val/imagenet

measurement:
  operator:
    name: lensless_turing
    kernel_size: 256
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.002
