conditioning:
  method:  ps_conv
  params:
    scale: 1.0
    diff_scale: 1.0
    deconv_scale: 1.0
    kernel_size: 256
    exp_task: lensless_voronoi_syn_ffhq_dps

    YS : 0
    

data:
  name: ffhq 
  root: ./samples/dps_val/ffhq 

measurement:
  operator:
    name: lensless
    kernel_size: 256
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.002
