conditioning:
  method: ps_conv #ps_deconv #ps_roi_deconv_patch_various_mask
  params:
    scale: 1.0
    diff_scale: 1.0
    deconv_scale: 1.0
    kernel_size: 256
    exp_task: motion_deblur_imagenet_dps

    YS : 0


data:
  name: imagenet #ffhq
  root: ./samples/dps_val/imagenet #./data/samples/
  
measurement:
  operator:
    name: motion_blur
    kernel_size: 256 #61
    intensity: 1.0 #0.5

  noise: 
    name: gaussian
    sigma: 0.0005 
